# installer/build_thresholds_iss.py
"""
Reads system_check_constants.py and writes installer/thresholds.iss as a
Pascal const declaration block. Run before ISCC.exe to keep the Inno
installer's threshold values in sync with the Python classifier.

Usage:
    python installer/build_thresholds_iss.py
"""

import os
import sys

# Ensure we can import from the project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from system_check_constants import (
    RAM_BLOCKED_MIN_GB,
    DISK_BLOCKED_MIN_FREE_GB,
    WIN_BLOCKED_MIN_BUILD,
    CORES_MIN_RECOMMENDED,
    RAM_MIN_RECOMMENDED_GB,
    CPU_LOW_POWER_PATTERNS,
)

OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "thresholds.iss")

# PascalScript (Inno Setup) does NOT support typed array constants in
# const blocks. We emit a delimited string instead and let the consumer
# split on '|' at runtime in IsLowPowerCpu.
PIPE_DELIMITED = "|".join(CPU_LOW_POWER_PATTERNS)

content = f"""; AUTO-GENERATED by installer/build_thresholds_iss.py
; DO NOT EDIT BY HAND — run the codegen script after changing
; system_check_constants.py.

#define RAM_BLOCKED_MIN_GB {RAM_BLOCKED_MIN_GB}
#define DISK_BLOCKED_MIN_FREE_GB {DISK_BLOCKED_MIN_FREE_GB}
#define WIN_BLOCKED_MIN_BUILD {WIN_BLOCKED_MIN_BUILD}
#define CORES_MIN_RECOMMENDED {CORES_MIN_RECOMMENDED}
#define RAM_MIN_RECOMMENDED_GB {RAM_MIN_RECOMMENDED_GB}

; Pipe-delimited list of low-power CPU substring patterns. Consumed by
; IsLowPowerCpu in system_check.iss via a Pos-based scan (PascalScript
; const blocks don't support typed array constants).
#define CPU_LOW_POWER_PATTERNS_PIPE "{PIPE_DELIMITED}"
"""

with open(OUTPUT, "w", encoding="utf-8", newline="\r\n") as f:
    f.write(content)

print(f"Wrote {OUTPUT}")
print(f"  Constants: {len(CPU_LOW_POWER_PATTERNS)} CPU patterns, "
      f"RAM_BLOCKED_MIN={RAM_BLOCKED_MIN_GB}GB, "
      f"CORES_MIN_RECOMMENDED={CORES_MIN_RECOMMENDED}")
