; AUTO-GENERATED by installer/build_thresholds_iss.py
; DO NOT EDIT BY HAND — run the codegen script after changing
; system_check_constants.py.

#define RAM_BLOCKED_MIN_GB 2
#define DISK_BLOCKED_MIN_FREE_GB 4
#define WIN_BLOCKED_MIN_BUILD 19041
#define CORES_MIN_RECOMMENDED 4
#define RAM_MIN_RECOMMENDED_GB 8

[Code]
const
  CPU_LOW_POWER_PATTERN_COUNT = 13;
  CPU_LOW_POWER_PATTERNS: array[0..12] of String = (
    'atom',
    'celeron',
    'pentium silver',
    'pentium gold',
    'pentium n',
    ' n100',
    ' n200',
    ' n300',
    ' n4000',
    ' n5000',
    ' n6000',
    ' n95',
    ' n97'
  );
